/*
 * File: app/store/countrySmallStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.store.countrySmallStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field',
        'Ext.util.Grouper'
    ],

    config: {
        data: [
            {
                name: 'Afghanistan<br>2 lines',
                code: 'AF',
                cls: 'triangle bottom-left red'
            },
            {
                name: 'Åland Islands',
                code: 'AX'
            },
            {
                name: 'Albania',
                code: 'AL',
                color1: 'green',
                color2: 'green'
            },
            {
                name: 'Algeria',
                code: 'DZ',
                cls: 'triangle top-left teal'
            },
            {
                name: 'American Samoa',
                code: 'AS'
            },
            {
                name: 'Andorra',
                code: 'AD',
                cls: 'triangle bottom-right orange'
            },
            {
                name: 'Angola',
                code: 'AO'
            },
            {
                name: 'Anguilla',
                code: 'AI',
                cls: 'triangle top-right lime'
            },
            {
                name: 'Antarctica',
                code: 'AQ',
                cls: 'triangle bottom-left deeporange'
            },
            {
                name: 'Antigua and Barbuda',
                code: 'AG',
                cls: 'triangle bottom-left orange'
            },
            {
                name: 'Argentina',
                code: 'AR',
                cls: 'triangle bottom-left lime'
            },
            {
                name: 'Armenia',
                code: 'AM',
                cls: 'triangle bottom-left pink'
            },
            {
                name: 'Aruba',
                code: 'AW',
                cls: 'triangle bottom-left lime'
            },
            {
                name: 'Australia',
                code: 'AU'
            },
            {
                name: 'Austria',
                code: 'AT',
                color1: 'red',
                color2: 'red'
            },
            {
                name: 'Azerbaijan',
                code: 'AZ'
            },
            {
                name: 'Bahamas',
                code: 'BS'
            },
            {
                name: 'Bahrain',
                code: 'BH'
            },
            {
                name: 'Bangladesh',
                code: 'BD'
            },
            {
                name: 'Barbados',
                code: 'BB'
            },
            {
                name: 'Belarus',
                code: 'BY'
            },
            {
                name: 'Belgium',
                code: 'BE'
            },
            {
                name: 'Belize',
                code: 'BZ'
            },
            {
                name: 'Benin',
                code: 'BJ'
            },
            {
                name: 'Bermuda',
                code: 'BM'
            },
            {
                name: 'Bhutan',
                code: 'BT'
            },
            {
                name: 'Bolivia',
                code: 'BO'
            },
            {
                name: 'Bosnia and Herzegovina',
                code: 'BA'
            },
            {
                name: 'Botswana',
                code: 'BW'
            },
            {
                name: 'Bouvet Island',
                code: 'BV'
            },
            {
                name: 'Brazil',
                code: 'BR'
            },
            {
                name: 'British Indian Ocean Territory',
                code: 'IO'
            },
            {
                name: 'Brunei Darussalam',
                code: 'BN'
            },
            {
                name: 'Bulgaria',
                code: 'BG'
            },
            {
                name: 'Burkina Faso',
                code: 'BF'
            },
            {
                name: 'Burundi',
                code: 'BI'
            },
            {
                name: 'Cambodia',
                code: 'KH'
            },
            {
                name: 'Cameroon',
                code: 'CM'
            },
            {
                name: 'Canada',
                code: 'CA'
            },
            {
                name: 'Cape Verde',
                code: 'CV'
            },
            {
                name: 'Cayman Islands',
                code: 'KY'
            },
            {
                name: 'Central African Republic',
                code: 'CF'
            },
            {
                name: 'Chad',
                code: 'TD'
            },
            {
                name: 'Chile',
                code: 'CL'
            },
            {
                name: 'China',
                code: 'CN'
            },
            {
                name: 'Christmas Island',
                code: 'CX'
            },
            {
                name: 'Cocos (Keeling) Islands',
                code: 'CC'
            },
            {
                name: 'Colombia',
                code: 'CO'
            },
            {
                name: 'Comoros',
                code: 'KM'
            },
            {
                name: 'Congo',
                code: 'CG'
            },
            {
                name: 'Congo, The Democratic Republic of the',
                code: 'CD'
            },
            {
                name: 'Cook Islands',
                code: 'CK'
            },
            {
                name: 'Costa Rica',
                code: 'CR'
            },
            {
                name: 'Cote D\'Ivoire',
                code: 'CI'
            },
            {
                name: 'Croatia',
                code: 'HR'
            },
            {
                name: 'Cuba',
                code: 'CU'
            },
            {
                name: 'Cyprus',
                code: 'CY'
            },
            {
                name: 'Czech Republic',
                code: 'CZ'
            }
        ],
        storeId: 'countrySmallStore',
        fields: [
            {
                name: 'name'
            },
            {
                name: 'code'
            },
            {
                name: 'color1'
            },
            {
                name: 'color2'
            },
            {
                name: 'cls'
            }
        ],
        grouper: {
            groupFn: function(item) {
                return item.get('name')[0];
            }
        }
    }
});