/*
 * File: app/view/Backgrounds.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.Backgrounds', {
    extend: 'Ext.Container',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'list',
                data: [
                    {
                        name: 'Light',
                        file: 'background.jpg'
                    },
                    {
                        name: 'Light 1',
                        file: 'background-1.jpg'
                    },
                    {
                        name: 'Light 2',
                        file: 'background-2.jpg'
                    },
                    {
                        name: 'Light 3',
                        file: 'background-3.jpg'
                    },
                    {
                        name: 'Light 4',
                        file: 'background-4.jpg'
                    },
                    {
                        name: 'Dark',
                        file: 'background-dark.jpg'
                    }
                ],
                itemId: 'listBackgrounds',
                itemTpl: [
                    '<div>{name}</div>'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onListBackgroundsSelect',
                event: 'select',
                delegate: '#listBackgrounds'
            }
        ]
    },

    onListBackgroundsSelect: function(dataview, record, eOpts) {
        Ext.Viewport.element.dom.firstChild.style.backgroundImage = 'url(resources/images/' + record.get('file') + ')';
    }

});