/*
 * File: app/view/Buttons.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.Buttons', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Spacer',
        'Ext.Button',
        'Ext.SegmentedButton'
    ],

    config: {
        itemId: 'Buttons',
        layout: 'vbox',
        defaults: {
            flex: 1
        },
        items: [
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            margin: '0 3',
                            //style: 'font-size: 0.8em;',
                            height: 45,
                            minWidth: 100
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'red',
                                text: 'red'
                            },
                            {
                                xtype: 'button',
                                ui: 'pink',
                                text: 'pink'
                            },
                            {
                                xtype: 'button',
                                ui: 'purple',
                                text: 'purple'
                            },
                            {
                                xtype: 'button',
                                ui: 'deeppurple',
                                text: 'deeppurple'
                            },
                            {
                                xtype: 'button',
                                ui: 'indigo',
                                text: 'indigo'
                            },
                            {
                                xtype: 'button',
                                ui: 'blue',
                                text: 'blue'
                            },
                            {
                                xtype: 'button',
                                ui: 'lightblue',
                                text: 'lightblue'
                            },
                            {
                                xtype: 'button',
                                ui: 'cyan',
                                text: 'cyan'
                            },
                            {
                                xtype: 'button',
                                ui: 'teal',
                                text: 'teal'
                            },
                            {
                                xtype: 'button',
                                ui: 'green',
                                text: 'green'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            margin: '0 3',
                            //style: 'font-size: 0.8em;',
                            height: 45,
                            minWidth: 100
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'lightgreen',
                                text: 'lightgreen'
                            },
                            {
                                xtype: 'button',
                                ui: 'lime',
                                text: 'lime'
                            },
                            {
                                xtype: 'button',
                                ui: 'yellow',
                                text: 'yellow'
                            },
                            {
                                xtype: 'button',
                                ui: 'amber',
                                text: 'amber'
                            },
                            {
                                xtype: 'button',
                                ui: 'orange',
                                text: 'orange'
                            },
                            {
                                xtype: 'button',
                                ui: 'deeporange',
                                text: 'deeporange'
                            },
                            {
                                xtype: 'button',
                                ui: 'brown',
                                text: 'brown'
                            },
                            {
                                xtype: 'button',
                                ui: 'grey',
                                text: 'grey'
                            },
                            {
                                xtype: 'button',
                                ui: 'bluegrey',
                                text: 'bluegrey'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                text: 'x-button'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                text: 'x-buton-pressing'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                text: 'x-button-pressed'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                text: 'x-item-disabled'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'plain',
                                text: 'Plain'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                cls: 'x-button-pressing',
                                ui: 'plain',
                                text: 'Plain'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                cls: 'x-button-pressed',
                                ui: 'plain',
                                text: 'Plain'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                ui: 'plain',
                                text: 'Plain'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                text: 'Normal'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                text: 'Normal'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                text: 'Normal'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                text: 'Normal'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'action',
                                text: 'Action'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'action',
                                text: 'Action'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'action',
                                text: 'Action'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'action',
                                text: 'Action'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'action-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'base',
                                text: 'Base'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'base',
                                text: 'Base'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'base',
                                text: 'Base'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'base',
                                text: 'Base'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'base-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'decline',
                                text: 'Decline'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'decline',
                                text: 'Decline'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'decline',
                                text: 'Decline'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'decline',
                                text: 'Decline'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'decline-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'confirm',
                                text: 'Confirm'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'confirm',
                                text: 'Confirm'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'confirm',
                                text: 'Confirm'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'confirm',
                                text: 'Confirm'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-round',
                                text: 'Round'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'confirm-small',
                                text: 'Small'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 4,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'back',
                                text: 'Back'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'segmentedbutton',
                                items: [
                                    {
                                        xtype: 'button',
                                        pressed: true,
                                        text: 'Left'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Center'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Right'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'forward',
                                text: 'Forward'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressing'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'back',
                                text: 'Back'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'segmentedbutton',
                                defaults: {
                                    cls: 'x-button-pressing'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        pressed: true,
                                        text: 'Left'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Center'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Right'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'forward',
                                text: 'Forward'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            cls: 'x-button-pressed'
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'back',
                                text: 'Back'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'segmentedbutton',
                                defaults: {
                                    cls: 'x-button-pressed'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        pressed: true,
                                        text: 'Left'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Center'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Right'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'forward',
                                text: 'Forward'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 4,
                        height: '',
                        width: '100%',
                        defaults: {
                            disabled: true
                        },
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                height: '',
                                ui: 'back',
                                text: 'Back'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'segmentedbutton',
                                defaults: {
                                    disabled: true
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        pressed: true,
                                        text: 'Left'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Center'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Right'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                ui: 'forward',
                                text: 'Forward'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});