/*
 * File: app/view/Carousel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.Carousel', {
    extend: 'Ext.Container',

    requires: [
        'Ext.carousel.Carousel',
        'Ext.Label'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'carousel',
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 20
            },
            {
                xtype: 'carousel',
                flex: 1,
                direction: 'vertical',
                items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'label',
                                centered: true,
                                html: 'Test'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});