/*
 * File: app/view/FontAwesome.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.FontAwesome', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Container',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
        defaults: {
            margin: 10
        },
        items: [
            {
                xtype: 'container',
                defaults: {
                    margin: 5
                },
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'my-fa-file-o',
                        text: 'New'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'my-fa-save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'my-fa-trash-o',
                        text: 'Delete'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'my-fa-copy',
                        text: 'Copy'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'my-fa-paste',
                        text: 'Paste'
                    },
                    {
                        xtype: 'label',
                        html: 'added to theme'
                    }
                ]
            },
            {
                xtype: 'container',
                defaults: {
                    margin: 5
                },
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-file-o',
                        text: 'New'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-trash-o',
                        text: 'Delete'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-copy',
                        text: 'Copy'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-paste',
                        text: 'Paste'
                    },
                    {
                        xtype: 'label',
                        html: 'from font awesome css'
                    }
                ]
            },
            {
                xtype: 'container',
                defaults: {
                    margin: 5
                },
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-plus',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-minus',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-times',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-chevron-left',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-chevron-right',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-crosshairs',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-lock',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-unlock',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-square-o',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa fa-check-square-o',
                        text: ''
                    }
                ]
            }
        ]
    }

});