/*
 * File: app/view/FormsAndPanels.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.FormsAndPanels', {
    extend: 'Ext.Container',

    requires: [
        'Ext.form.Panel',
        'Ext.field.Text'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'formpanel',
                flex: 1,
                items: [
                    {
                        xtype: 'textfield',
                        label: 'From Field'
                    },
                    {
                        xtype: 'container',
                        html: '<span class="font-red">red</span>  <span class="font-pink">pink</span>  <span class="font-purple">purple</span>  <span class="font-deeppurple">deeppurple</span>  <span class="font-indigo">indigo</span>  <span class="font-blue">blue</span>  <span class="font-lightblue">lightblue</span>  <span class="font-cyan">cyan</span>  <span class="font-teal">teal</span>  <span class="font-green">green</span>  <span class="font-lightgreen">lightgreen</span>  <span class="font-lime">lime</span>  <span class="font-yellow">yellow</span>  <span class="font-amber">amber</span>  <span class="font-orange">orange</span>  <span class="font-deeporange">deeporange</span>  <span class="font-brown">brown</span>  <span class="font-grey">grey</span>  <span class="font-bluegrey">bluegrey</span> ',
                        padding: 10
                    }
                ]
            },
            {
                xtype: 'container',
                width: 20
            },
            {
                xtype: 'panel',
                flex: 1,
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Panel Field'
                    },
                    {
                        xtype: 'container',
                        html: '<span class="badge red">red</span> <span class="badge pink">pink</span> <span class="badge purple">purple</span> <span class="badge deeppurple">deeppurple</span> <span class="badge indigo">indigo</span> <span class="badge blue">blue</span> <span class="badge lightblue">lightblue</span> <span class="badge cyan">cyan</span> <span class="badge teal">teal</span> <span class="badge green">green</span> <span class="badge lightgreen">lightgreen</span> <span class="badge lime">lime</span> <span class="badge yellow">yellow</span> <span class="badge amber">amber</span> <span class="badge orange">orange</span> <span class="badge deeporange">deeporange</span> <span class="badge brown">brown</span> <span class="badge grey">grey</span> <span class="badge bluegrey">bluegrey</span>',
                        padding: 10
                    }
                ]
            }
        ]
    }

});