/*
 * File: app/view/Grid.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.Grid', {
    extend: 'Ext.Container',

    requires: [
        'Ext.grid.Grid',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'grid',
                store: 'countryStore',
                title: 'Grid',
                columns: [
                    {
                        xtype: 'column',
                        width: 300,
                        dataIndex: 'name',
                        text: 'String'
                    },
                    {
                        xtype: 'datecolumn',
                        width: 110,
                        dataIndex: 'date',
                        text: 'Date'
                    },
                    {
                        xtype: 'booleancolumn',
                        width: 110,
                        dataIndex: 'bool',
                        text: 'Boolean'
                    }
                ]
            }
        ]
    }

});