/*
 * File: app/view/ListSelection.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.ListSelection', {
    extend: 'Ext.Container',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        centered: false,
        layout: 'hbox',
        defaults: {
            margin: 5,
            cls: 'md-shadow'
        },
        items: [
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'md-shadow',
                    'radio-selection'
                ],
                itemTpl: [
                    '<div class="flexbox">',
                    '    <div class="radio"></div>',
                    '    <div class="flex1 text">',
                    '        <div>{name}</div>',
                    '    </div>',
                    '</div>'
                ],
                store: 'countrySmallStore'
            },
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'md-shadow',
                    'check-selection'
                ],
                mode: 'SIMPLE',
                itemTpl: [
                    '<div class="flexbox">',
                    '    <div class="tick"></div>',
                    '    <div class="flex1 text">',
                    '        <div>{name}</div>',
                    '    </div>',
                    '</div>'
                ],
                store: 'countrySmallStore'
            }
        ]
    }

});