/*
 * File: app/view/List.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.List', {
    extend: 'Ext.Container',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        centered: false,
        layout: 'hbox',
        defaults: {
            margin: 10,
            cls: 'md-shadow'
        },
        items: [
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'smaller-padding',
                    'with-disclosure',
                    'md-shadow'
                ],
                itemTpl: [
                    '<div class="flexbox">',
                    '    <div class="flex1 text">',
                    '        <div>{name}</div>',
                    '        <div class="smaller-font">Smaller font...</div>',
                    '    </div>',
                    '    <div class="flexbox items-center">',
                    '        <div class="badge list-badge">{code}</div>',
                    '    </div>',
                    '</div>'
                ],
                store: 'countrySmallStore',
                grouped: true,
                onItemDisclosure: true
            },
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'with-disclosure',
                    'smaller-padding',
                    'md-shadow'
                ],
                itemTpl: [
                    '<div class="flexbox">',
                    '    <div class="flex1 text">',
                    '        <div>{name} ({code})</div>',
                    '        <div class="smallest-font">Smallest font...</div>',
                    '    </div>',
                    '    <div class="markers vertical">',
                    '        <div class="fa fa-info-circle"></div>',
                    '        <div class="fa fa-plus-circle font-green"></div>',
                    '        <div class="fa fa-minus-circle font-deeporange"></div>',
                    '    </div>',
                    '</div>'
                ],
                store: 'countrySmallStore',
                grouped: false,
                onItemDisclosure: true
            },
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'smaller-padding',
                    'with-disclosure',
                    'md-shadow'
                ],
                itemTpl: [
                    '<div class="strip left bg-{color1}"></div>',
                    '<div class="strip right bg-{color2}"></div>',
                    '<tpl if="cls"><div class="{cls}"></div></tpl>',
                    '',
                    '<div class="flexbox">',
                    '    <div class="flex1 flexbox wrap">',
                    '        <div class="flex1 text">{code}</div>',
                    '        <div class="flex3 text">{name}</div>',
                    '        <div class="smaller-font fullflex">Some text for description...</div>',
                    '    </div>',
                    '    <div class="markers">',
                    '        <div class="fa fa-info-circle"></div>',
                    '        <div class="fa fa-plus-circle font-green"></div>',
                    '        <div class="fa fa-minus-circle font-deeporange"></div>',
                    '    </div>',
                    '    <div class="person-image" style="background-image: url(\'resources/images/person.png\');"></div>',
                    '</div>'
                ],
                store: 'countrySmallStore',
                grouped: false,
                onItemDisclosure: true
            }
        ]
    }

});