/*
 * File: app/view/List.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.List', {
    extend: 'Ext.Container',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        centered: false,
        layout: 'hbox',
        items: [
            {
                xtype: 'list',
                flex: 1,
                cls: [
                    'with-person-image',
                    'with-markers',
                    'flexbox'
                ],
                height: '100%',
                itemTpl: [
                    '<div class="flex1">{code}</div>',
                    '<div class="flex3">{name}</div>',
                    '',
                    '<div class="strip left bg-{color1}"></div>',
                    '<div class="strip right bg-{color2}"></div>',
                    '',
                    '<div class="markers-container">',
                    '    <div class="markers">',
                    '        <div class="fa fa-info-circle"></div>',
                    '        <div class="fa fa-minus-circle font-deeporange"></div>',
                    '    </div>',
                    '</div>',
                    '',
                    '<div class="person-image" style="background-image: url(\'resources/images/person.png\');"></div>',
                    '',
                    '<tpl if="cls"><div class="{cls}"></div></tpl>'
                ],
                store: 'countryStore',
                grouped: false,
                itemHeight: 68
            },
            {
                xtype: 'container',
                width: 20
            },
            {
                xtype: 'list',
                flex: 1,
                height: '100%',
                itemTpl: [
                    '<div>{name} ({code})</div>',
                    '<div class="smaller-font">Some description...</div>'
                ],
                store: 'countryStore',
                grouped: true
            },
            {
                xtype: 'container',
                width: 20
            },
            {
                xtype: 'list',
                flex: 1,
                height: '100%',
                itemTpl: [
                    '<div>{name} ({code})</div>',
                    '<div class="smallest-font">Some info...</div>'
                ],
                store: 'countryStore',
                grouped: false,
                onItemDisclosure: true
            },
            {
                xtype: 'container',
                width: 20
            },
            {
                xtype: 'list',
                flex: 1,
                deferEmptyText: false,
                emptyText: 'List is empty',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'emptyStore'
            }
        ]
    }

});