/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.Login', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Panel',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'panel',
                centered: true,
                modal: true,
                items: [
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: 'User'
                    },
                    {
                        xtype: 'passwordfield',
                        clearIcon: false,
                        label: 'Pin'
                    },
                    {
                        xtype: 'container',
                        padding: 5,
                        defaults: {
                            defaults: {
                                flex: 1,
                                height: 75,
                                margin: 5
                            }
                        },
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        text: '1'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '2'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '3'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        text: '4'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '5'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '6'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        text: '7'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '8'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '9'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        ui: 'decline',
                                        text: 'C'
                                    },
                                    {
                                        xtype: 'button',
                                        text: '0'
                                    },
                                    {
                                        xtype: 'button',
                                        ui: 'confirm',
                                        text: 'OK'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});