/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouchTheme.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.mainview',

    requires: [
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.navigation.View',
        'Ext.navigation.Bar'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'titlebar',
                cls: 'md-shadow',
                docked: 'top',
                zIndex: 1,
                title: 'Custom Theme',
                items: [
                    {
                        xtype: 'button',
                        align: 'right',
                        itemId: 'btnHelp',
                        ui: 'plain',
                        iconCls: 'fa fa-question',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'border-right',
                ui: 'dark',
                width: 300,
                items: [
                    {
                        xtype: 'list',
                        data: [
                            {
                                title: 'Buttons',
                                view: 'Buttons'
                            },
                            {
                                title: 'Carousel',
                                view: 'Carousel'
                            },
                            {
                                title: 'Fields and Radios',
                                view: 'FieldsAndRadios'
                            },
                            {
                                title: 'Font Awesome',
                                view: 'FontAwesome'
                            },
                            {
                                title: 'Forms and Panels',
                                view: 'FormsAndPanels'
                            },
                            /*{title: 'Grid', view: 'Grid'},*/{
                                title: 'List',
                                view: 'List'
                            },
                            {
                                title: 'List Buffered',
                                view: 'ListBuffered'
                            },
                            {
                                title: 'List Round',
                                view: 'ListRound'
                            },
                            {
                                title: 'Login',
                                view: 'Login'
                            },
                            {
                                title: 'Load Mask',
                                view: 'LoadMask'
                            },
                            {
                                title: 'Overlays',
                                view: 'Overlays'
                            },
                            {
                                title: 'Tabs',
                                view: 'Tabs'
                            },
                            {
                                title: 'Toolbars',
                                view: 'Toolbars'
                            },
                            {
                                title: 'Backgrounds',
                                view: 'Backgrounds'
                            }
                        ],
                        height: '100%',
                        itemId: 'navList',
                        itemTpl: [
                            '<div>{title}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'navigationview',
                flex: 3,
                itemId: 'mainContent',
                margin: 20,
                layout: {
                    type: 'card',
                    animation: false,
                    'animation.direction': 'down'
                },
                navigationBar: {
                    docked: 'bottom',
                    hidden: true
                }
            }
        ]
    }

});